#!/bin/sh
xset -dpms     # disable DPMS (Energy Star) features.
xset s off       # disable screen saver
xset s noblank # don't blank the video device
sleep 10
unclutter &
matchbox-window-manager &
midori -e Fullscreen -a "http://monitoring01.xamance.net/Naglite3/"
